In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Datasets/heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [ ]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [ ]:
X=df.iloc[:,:-1]
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3

In [ ]:
y=df.iloc[:,-1]
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_scaled=scaler.fit_transform(X)
X_scaled

array([[0.47916667, 1.        , 0.        , ..., 1.        , 0.5       ,
        1.        ],
       [0.5       , 1.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.85416667, 1.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.375     , 1.        , 0.        , ..., 0.5       , 0.25      ,
        0.66666667],
       [0.4375    , 0.        , 0.        , ..., 1.        , 0.        ,
        0.66666667],
       [0.52083333, 1.        , 0.        , ..., 0.5       , 0.25      ,
        1.        ]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.3,random_state=1)

In [ ]:
X_train.shape,y_train.shape

((717, 13), (717,))

In [ ]:
X_test.shape,y_test.shape

((308, 13), (308,))

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
knn=KNeighborsClassifier(n_neighbors=3)
sv=SVC(kernel='poly')
nb=GaussianNB()
models=[knn,sv,nb]
for model in models:
  print("*****************",model,"*****************")
  model.fit(X_train,y_train)
  y_pred=model.predict(X_test)
  print(classification_report(y_test,y_pred))

***************** KNeighborsClassifier(n_neighbors=3) *****************
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       161
           1       0.95      0.96      0.96       147

    accuracy                           0.96       308
   macro avg       0.96      0.96      0.96       308
weighted avg       0.96      0.96      0.96       308

***************** SVC(kernel='poly') *****************
              precision    recall  f1-score   support

           0       0.97      0.81      0.89       161
           1       0.83      0.97      0.89       147

    accuracy                           0.89       308
   macro avg       0.90      0.89      0.89       308
weighted avg       0.90      0.89      0.89       308

***************** GaussianNB() *****************
              precision    recall  f1-score   support

           0       0.87      0.71      0.78       161
           1       0.73      0.88      0.80       147

    accuracy                           0.79       308
   macro avg       0.80      0.80      0.79       308
weighted avg       0.81      0.79      0.79       308

In [ ]:
df.corr()['target']

age        -0.229324
sex        -0.279501
cp          0.434854
trestbps   -0.138772
chol       -0.099966
fbs        -0.041164
restecg     0.134468
thalach     0.422895
exang      -0.438029
oldpeak    -0.438441
slope       0.345512
ca         -0.382085
thal       -0.337838
target      1.000000
Name: target, dtype: float64

In [ ]:
X=X.drop(['chol','fbs'],axis=1)
X

,age,sex,cp,trestbps,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,1,168,0,1.0,2,2,3
1,53,1,0,140,0,155,1,3.1,0,0,3
2,70,1,0,145,1,125,1,2.6,0,0,3
3,61,1,0,148,1,161,0,0.0,2,1,3
4,62,0,0,138,1,106,0,1.9,1,3,2
...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,1,164,1,0.0,2,0,2
1021,60,1,0,125,0,141,1,2.8,1,1,3
1022,47,1,0,110,0,118,1,1.0,1,1,2
1023,50,0,0,110,0,159,0,0.0,2,0,2
1024,54,1,0,120,1,113,0,1.4,1,1,3

In [ ]:
X_scaled=scaler.fit_transform(X)
X_scaled

array([[0.47916667, 1.        , 0.        , ..., 1.        , 0.5       ,
        1.        ],
       [0.5       , 1.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.85416667, 1.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.375     , 1.        , 0.        , ..., 0.5       , 0.25      ,
        0.66666667],
       [0.4375    , 0.        , 0.        , ..., 1.        , 0.        ,
        0.66666667],
       [0.52083333, 1.        , 0.        , ..., 0.5       , 0.25      ,
        1.        ]])

In [ ]:

X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.3,random_state=1)

In [ ]:
X_train.shape,y_train.shape

((717, 11), (717,))

In [ ]:
X_test.shape,y_test.shape

((308, 11), (308,))

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
knn1=KNeighborsClassifier(n_neighbors=3)
sv1=SVC(kernel='poly')
nb1=GaussianNB()
models=[knn1,sv1,nb1]
for model in models:
  print("*****************",model,"*****************")
  model.fit(X_train,y_train)
  y_pred1=model.predict(X_test)
  print(classification_report(y_test,y_pred1))

***************** KNeighborsClassifier(n_neighbors=3) *****************
              precision    recall  f1-score   support

           0       0.94      0.93      0.93       161
           1       0.92      0.94      0.93       147

    accuracy                           0.93       308
   macro avg       0.93      0.93      0.93       308
weighted avg       0.93      0.93      0.93       308

***************** SVC(kernel='poly') *****************
              precision    recall  f1-score   support

           0       0.96      0.83      0.89       161
           1       0.84      0.97      0.90       147

    accuracy                           0.89       308
   macro avg       0.90      0.90      0.89       308
weighted avg       0.90      0.89      0.89       308

***************** GaussianNB() *****************
              precision    recall  f1-score   support

           0       0.85      0.71      0.77       161
           1       0.73      0.86      0.79       147

    accuracy                           0.78       308
   macro avg       0.79      0.79      0.78       308
weighted avg       0.79      0.78      0.78       308